services:
  sut:
    image: sut
    volumes:
      - ./tests:/tests:ro
    entrypoint: ["/bin/bash", "-ec"]
    command:
      - |
        for t in /tests/*.sh; do
          echo "== $${t} =="
          bash "$${t}"
        done
